---
site_name: Chrome Version
site_description: Chrome Version
site_url: https://hasansezertasan.github.io/chrome-version/
repo_name: hasansezertasan/chrome-version
repo_url: https://github.com/hasansezertasan/chrome-version
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
          icon: material/weather-night
          name: Switch to light mode
  features:
    - navigation.instant
    - navigation.top
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
plugins:
  - search
  - mkdocstrings
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - tables
  - def_list
nav:
  - Home: index.md
  - API Reference: reference.md
  - Changelog: changelog.md
